# Generated by Django 2.0.2 on 2018-05-29 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('actor_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_name', models.CharField(max_length=32, verbose_name='演员姓名')),
                ('actor_gender', models.CharField(max_length=32, verbose_name='演员性别')),
                ('actor_birth', models.DateTimeField(verbose_name='演员生日')),
                ('actor_nationality', models.CharField(max_length=32, verbose_name='演员国籍')),
            ],
            options={
                'verbose_name': '演员',
                'verbose_name_plural': '演员',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=32, verbose_name='电影类别')),
            ],
            options={
                'verbose_name': '电影类别',
                'verbose_name_plural': '电影类别',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_author', models.CharField(max_length=50, verbose_name='评论作者')),
                ('comment_detail', models.CharField(max_length=2000, verbose_name='评论详情')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name_en', models.CharField(max_length=64, verbose_name='英文名')),
                ('movie_name_cn', models.CharField(max_length=64, verbose_name='中文名')),
                ('movie_age', models.IntegerField(verbose_name='年代')),
                ('movie_where', models.CharField(max_length=32, verbose_name='产地')),
                ('movie_language', models.CharField(max_length=32, verbose_name='语言')),
                ('movie_date', models.CharField(max_length=255, verbose_name='上映日期')),
                ('movie_length', models.CharField(max_length=255, verbose_name='片长')),
                ('movie_director', models.CharField(max_length=128, verbose_name='导演')),
                ('movie_describe', models.CharField(max_length=2000, verbose_name='简介')),
                ('movie_image', models.CharField(max_length=255, verbose_name='封面')),
                ('to_actor', models.ManyToManyField(to='urmovie.Actor', verbose_name='演员')),
                ('to_category', models.ManyToManyField(to='urmovie.Category', verbose_name='类别')),
            ],
            options={
                'verbose_name': '电影',
                'verbose_name_plural': '电影',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_belong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='urmovie.Movie', verbose_name='评论源'),
        ),
    ]
