# Generated by Django 2.0.2 on 2018-05-31 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urmovie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_belong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urmovie.Movie', verbose_name='评论源'),
        ),
    ]
