# Generated by Django 2.0.2 on 2018-05-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('host_id', models.AutoField(primary_key=True, serialize=False)),
                ('host_name', models.CharField(db_index=True, max_length=64, verbose_name='主机名')),
                ('host_ip', models.GenericIPAddressField(db_index=True, verbose_name='主机ip')),
                ('host_port', models.IntegerField(verbose_name='主机端口')),
            ],
            options={
                'verbose_name': '主机',
                'verbose_name_plural': '主机',
            },
        ),
    ]
